version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    env_file:
      - ./env/frontend.env
    depends_on:
      - api
    volumes:
      - ./frontend/src:/usr/local/fe
  api:
    build: ./api
    ports:
      - 8080:8080
    env_file:
      - ./env/api.env
    volumes:
      - ./api/src:/usr/local/api